export const PROJECTS_REQUEST = "PROJECTS_REQUEST";
export const PROJECTS_SUCCESS = "PROJECTS_SUCCESS";
export const PROJECTS_FAILURE = "PROJECTS_FAILURE";

export const PROJECT_BY_ID_REQUEST = "PROJECT_BY_ID_REQUEST";
export const PROJECT_BY_ID_SUCCESS = "PROJECT_BY_ID_SUCCESS";
export const PROJECT_BY_ID_FAILURE = "PROJECT_BY_ID_FAILURE";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const DELETE_PROJECT_BY_ID_REQUEST = "DELETE_PROJECT_BY_ID_REQUEST";
export const DELETE_PROJECT_BY_ID_SUCCESS = "DELETE_PROJECT_BY_ID_SUCCESS";
export const DELETE_PROJECT_BY_ID_FAILURE = "DELETE_PROJECT_BY_ID_FAILURE";

export const SEARCH_PROJECTS_REQUEST = "SEARCH_PROJECTS_REQUEST";
export const SEARCH_PROJECTS_SUCCESS = "SEARCH_PROJECTS_SUCCESS";
export const SEARCH_PROJECTS_FAILURE = "SEARCH_PROJECTS_FAILURE";

export const INVITE_TO_PROJECT_REQUEST = "INVITE_TO_PROJECT_REQUEST";
export const INVITE_TO_PROJECT_SUCCESS = "INVITE_TO_PROJECT_SUCCESS";
export const INVITE_TO_PROJECT_FAILURE = "INVITE_TO_PROJECT_FAILURE";

export const ACCEPT_INVITATION_REQUEST = "ACCEPT_INVITATION_REQUEST";
export const ACCEPT_INVITATION_SUCCESS = "ACCEPT_INVITATION_SUCCESS";
export const ACCEPT_INVITATION_FAILURE = "ACCEPT_INVITATION_FAILURE";