export const TASKS_REQUEST = "TASKS_REQUEST";
export const TASKS_SUCCESS = "TASKS_SUCCESS";
export const TASKS_FAILURE = "TASKS_FAILURE";

export const TASK_BY_ID_REQUEST = "TASK_BY_ID_REQUEST";
export const TASK_BY_ID_SUCCESS = "TASK_BY_ID_SUCCESS";
export const TASK_BY_ID_FAILURE = "TASK_BY_ID_FAILURE";

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const DELETE_TASK_BY_ID_REQUEST = "DELETE_TASK_BY_ID_REQUEST";
export const DELETE_TASK_BY_ID_SUCCESS = "DELETE_TASK_BY_ID_SUCCESS";
export const DELETE_TASK_BY_ID_FAILURE = "DELETE_TASK_BY_ID_FAILURE";

export const UPDATE_TASK_STATUS_REQUEST = "UPDATE_TASK_STATUS_REQUEST";
export const UPDATE_TASK_STATUS_SUCCESS = "UPDATE_TASK_STATUS_SUCCESS";
export const UPDATE_TASK_STATUS_FAILURE = "UPDATE_TASK_STATUS_FAILURE";

export const ASSIGNEE_TASK_TO_USER_REQUEST = "ASSIGNEE_TASK_TO_USER_REQUEST";
export const ASSIGNEE_TASK_TO_USER_SUCCESS = "ASSIGNEE_TASK_TO_USER_SUCCESS";
export const ASSIGNEE_TASK_TO_USER_FAILURE = "ASSIGNEE_TASK_TO_USER_FAILURE";