export const MESSAGES_REQUEST = "MESSAGES_REQUEST";
export const MESSAGES_SUCCESS = "MESSAGES_SUCCESS";
export const MESSAGES_FAILURE = "MESSAGES_FAILURE";

export const SEND_MESSAGES_REQUEST = "SEND_MESSAGES_REQUEST";
export const SEND_MESSAGES_SUCCESS = "SEND_MESSAGES_SUCCESS";
export const SEND_MESSAGES_FAILURE = "SEND_MESSAGES_FAILURE";

export const CHAT_BY_PROJECT_ID_REQUEST = "CHAT_BY_PROJECT_ID_REQUEST";
export const CHAT_BY_PROJECT_ID_SUCCESS = "CHAT_BY_PROJECT_ID_SUCCESS";
export const CHAT_BY_PROJECT_ID_FAILURE = "CHAT_BY_PROJECT_ID_FAILURE";

export const CHAT_MESSAGES_REQUEST = "CHAT_MESSAGES_REQUEST";
export const CHAT_MESSAGES_SUCCESS = "CHAT_MESSAGES_SUCCESS";
export const CHAT_MESSAGES_FAILURE = "CHAT_MESSAGES_FAILURE";